-- begin DEMO_SPARE_PART
create unique index IDX_DEMO_SPARE_PART_UNIQ_CODE on DEMO_SPARE_PART (CODE) ^
create unique index IDX_DEMO_SPARE_PART_UNIQ_TITLE on DEMO_SPARE_PART (TITLE) ^
-- end DEMO_SPARE_PART
